version: '3'
volumes:
  letsencrypt_certs:
  letsencrypt_www:
  appdaemon_install:
services:

  samba:
    container_name: samba
    image: trnape/rpi-samba
    ports:
      - "445:445"
    volumes:
      - ./:/shared/hass
    restart: unless-stopped
    command: |
      -u "data:YOUR_SAMBA_PASSWORD" 
      -s "HassCfg:/shared/hass:rw:data"

  ftp:
    container_name: ftp
    image: stilliard/pure-ftpd:hardened
    ports:
      - "21:21"
    volumes:
      - "./ftp/data:/home/ftpusers/"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"

  homeassistant:
    container_name: hass
    build:
      context: ./virtualization/homeassistant/
      dockerfile: ./dockerfile
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt_certs:/etc/letsencrypt
    expose:
      - "8123"
    depends_on:
      - samba 
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  nginx:
    container_name: nginx
    build:
      context: ./virtualization/nginx/
      dockerfile: ./dockerfile
      args:
        - domain=YOUR_DOMAIN
    ports:
      - "80:80"
      - "443:443"
      - "8123:8123"
    depends_on:
      - homeassistant
    volumes:
      - letsencrypt_www:/var/www/letsencrypt
      - letsencrypt_certs:/etc/letsencrypt
    network_mode: host
    restart: unless-stopped

  letsencrypt:
    build:
      context: ./
      dockerfile: virtualization/letsencrypt/dockerfile
    entrypoint: ["/usr/scripts/check_certs.sh"]
    environment:
      - LETSENCRYPT_DOMAIN=YOUR_DOMAIN
      - LETSENCRYPT_EMAIL=YOUR_EMAIL
    depends_on:
      - nginx
    volumes:
      - letsencrypt_www:/var/www/letsencrypt
      - letsencrypt_certs:/etc/letsencrypt
      
  duckdns:
    build:
      context: ./
      dockerfile: virtualization/duckdns/dockerfile
    entrypoint: ["/usr/scripts/duck.sh"]
    environment:
      - DUCKDNS_DOMAIN=DUCKDNS_DOMAINNAME
      - DUCKDNS_TOKEN=DUCKDNS_TOKEN
    depends_on:
      - nginx
