version: '3'
volumes:
  letsencrypt_certs:
  letsencrypt_www:
  appdaemon_install:
services:

  samba:
    container_name: samba
    build:
      context: ./virtualization/samba/
      dockerfile: ./dockerfile
    ports:
      - "137-139:137-139"
      - "445:445"
    volumes:
      - .:/shared
      - /data/nas:/shared2
    restart: always

  mqtt:
    container_name: mqtt
    build:
      context: ./virtualization/mosquitto/
      dockerfile: ./dockerfile
    environment:
      - MQTT_USER=YOUR_MQTT_USER
      - YOUR_MQTT_PASSWDD
    ports:
      - "1883:1883"
      - "9001:9001"

  mysql:
    container_name: mysql
    image: hypriot/rpi-mysql
    network_mode: host
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=YOUR_HASS_DB_NAME
      - MYSQL_USER=YOUR_HASS_DB_USER
      - MYSQL_PASSWORD=YOUR_HASS_DB_PASSWD
    volumes:
      - /data/hass-db/mysql:/var/lib/mysql

  ftp:
    container_name: ftp
    image: stilliard/pure-ftpd:hardened
    ports:
      - "21:21"
    volumes:
      - "./ftp/data:/home/ftpusers/"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"

  homeassistant:
    container_name: hass
    build:
      context: ./virtualization/homeassistant/
      dockerfile: ./dockerfile
    volumes:
      - ./config:/config
      - /data/nas/hass:/data
      - /data/hass-db:/hass-db
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt_certs:/etc/letsencrypt
    expose:
      - "8123"
    depends_on:
      - samba 
      - mqtt 
      - mysql
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  appdaemon:
    container_name: appdaemon
    build:
      context: ./virtualization/appdaemon/
      dockerfile: ./dockerfile
    volumes:
      - ./config:/conf
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - homeassistant

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: virtualization/nginx/dockerfile
      args:
        - domain=YOUR_DOMAIN
    ports:
      - "80:80"
      - "443:443"
      - "8123:8123"
    depends_on:
      - homeassistant
    volumes:
      - letsencrypt_www:/var/www/letsencrypt
      - letsencrypt_certs:/etc/letsencrypt
    network_mode: host
    restart: always

  letsencrypt:
    build:
      context: ./
      dockerfile: virtualization/letsencrypt/dockerfile
    entrypoint: ["/usr/scripts/check_certs.sh"]
    environment:
      - LETSENCRYPT_DOMAIN=YOUR_DOMAIN
      - LETSENCRYPT_EMAIL=YOUR_EMAIL
    depends_on:
      - nginx
    volumes:
      - letsencrypt_www:/var/www/letsencrypt
      - letsencrypt_certs:/etc/letsencrypt
      
  duckdns:
    build:
      context: ./
      dockerfile: virtualization/duckdns/dockerfile
    entrypoint: ["/usr/scripts/duck.sh"]
    environment:
      - DUCKDNS_DOMAIN=DUCKDNS_DOMAINNAME
      - DUCKDNS_TOKEN=DUCKDNS_TOKEN
    depends_on:
      - nginx
