FROM resin/rpi-raspbian:jessie

RUN apt-get update && apt-get install -y wget && \
	wget -q -O - http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key | apt-key add - && \
	wget -q -O /etc/apt/sources.list.d/mosquitto-jessie.list http://repo.mosquitto.org/debian/mosquitto-jessie.list && \
	apt-get install -y mosquitto

RUN adduser --system --disabled-password --disabled-login mosquitto && \
	mkdir -m 1777 -p /mqtt/config /mqtt/config

COPY mosquitto.conf /mqtt/config/
COPY entrypoint.sh /

VOLUME ["/mqtt/data"]

EXPOSE 1883 9001

ENTRYPOINT ["/entrypoint.sh"]