default_view:
  view: yes
  name: Home
  entities:
    - group.family
    - group.weather

weather:
  name: Weather
  entities:
    - sensor.pws_weather_1d_metric
    - sensor.pws_feelslike_c
    - sensor.pws_temp_high_1d_c
    - sensor.pws_temp_low_1d_c
    - sensor.pws_precip_1d
    - sensor.pws_precip_1d_mm
    - sensor.pws_wind_1d_kph

power:
  view: yes
  name: Power
  entities:
    - group.power_switches

power_switches:
  view: no
  name: "Power Switches"
  entities: 
    - switch.tv_switch_bedroom_switch
    - switch.friteuse
    - switch.egg_cooker

family:
  name: Family
  view: no
  entities:
    - device_tracker.galaxys9home
    - device_tracker.alex_phone_samsung
    - input_boolean.working

sonos:
  name: Sonos
  view: yes
  entities:
    - media_player.kitchen
    - media_player.living_room
    - media_player.bathroom
    - media_player.master_bedroom
    - media_player.bureau


cameras:
  name: cameras
  view: yes
  entities:
    - camera.foscam_camera
    - camera.foscam_camera_2

system:
  name: System
  view: yes
  entities:
    - group.hardware
    - group.network
    - group.scripts
    - group.batteries

hardware:
  name: Hardware
  entities:
    - sensor.disk_use_percent_
    - sensor.log_db_file_size
    - sensor.memory_use_percent
    - sensor.last_boot
    - script.test

network:
  name: Network
  entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.ssl_cert_expiry

batteries:
  name: Batteries
  entities:
    - sensor.battery_livingroom_1
    - sensor.battery_livingroom_2
    - sensor.battery_kitchen
    - sensor.battery_bedroom
    - sensor.battery_bathroom
