FROM resin/raspberrypi3-python:3.6

VOLUME /conf
VOLUME /logs
VOLUME /certs
EXPOSE 5050

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN pip3 install --upgrade pip setuptools && \
	git clone https://github.com/home-assistant/appdaemon.git . && \
	pip3 install .

# hack to support symlinks in static folders
RUN sed -ri "s/add_static\((.*)\)/add_static\(\1, follow_symlinks=True\)/g" /usr/local/lib/python3.6/site-packages/appdaemon/rundash.py \
    && ln -s /conf/assets/javascript /usr/local/lib/python3.6/site-packages/appdaemon/assets/javascript/custom \
    && ln -s /conf/assets/images /usr/local/lib/python3.6/site-packages/appdaemon/assets/images/custom

# install hass-apps for heating schedule
RUN sudo pip install --upgrade hass-apps

CMD sudo appdaemon -c /conf
