- alias: "Reschedule"
  trigger: 
    - platform: state
      entity_id: input_boolean.auto_heat
    - platform: state
      entity_id: input_boolean.power_heat_bathroom
  action:
  - event: heaty_reschedule
    event_data:
      cancel_running_timer: True
- alias: "Turn off Powerheating"
  trigger:
    platform: state
    entity_id: input_boolean.power_heat_bathroom
    to: 'on'
    for:
      hours: 1
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.power_heat_bathroom
